### PR TITLE
[#200] tsquery boolean operators

### LINKED ISSUE #200: [ERROR] (ActiveRecord::StatementInvalid) PG::SyntaxError: ERROR: syntax error in tsquery
```
An ActiveRecord::StatementInvalid occurred in background at 2018-11-05 12:34:16 UTC :

PG::SyntaxError: ERROR: syntax error in tsquery: "(Supply & teacher & & & support & staff & cover.)"
: SELECT request_matches, relevance, resources.*
FROM resources,
LATERAL (SELECT ARRAY_AGG(DISTINCT rm[1])
FROM (SELECT ts_headline(LOWER(body), to_tsquery((SELECT array_to_string(ARRAY_AGG(
'(' || regexp_replace(keyword, ' +', ' & ', 'g') || ')'
), ' | ')
FROM (SELECT DISTINCT UNNEST(regexp_split_to_array(keywords, ', *'))
FROM resources _r
WHERE (
_r.resource_id = resources.resource_id AND
_r.resource_type = resources.resource_type AND
keywords IS NOT NULL AND
keywords <> ''
)
) AS T(keyword)
)))
FROM foi_requests
WHERE foi_requests.id = 864
LIMIT 1
) AS T(headline)
CROSS JOIN LATERAL regexp_matches(headline, '<b>(.*?)</b>', 'g') AS rm(matches)
) AS T1(request_matches),
LATERAL (SELECT ts_rank(
setweight(to_tsvector(title), 'B') ||
setweight(to_tsvector(COALESCE(summary, '')), 'C') ||
setweight(to_tsvector(keywords), 'A'),
to_tsquery(array_to_string(request_matches, ' & '))
)
) AS T2(relevance)
WHERE relevance > 0.5
ORDER BY relevance DESC, resource_id ASC
LIMIT 3

APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `async_exec'

-------------------------------
Backtrace:
-------------------------------

APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `async_exec'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:603:in `block (2 levels) in exec_no_cache'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_no_cache'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_no_cache'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:588:in `execute_and_clear'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:81:in `exec_query'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:465:in `select'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:57:in `select_all'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:99:in `block in select_all'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:122:in `block in cache_sql'
/opt/rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:108:in `cache_sql'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:99:in `select_all'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/querying.rb:41:in `find_by_sql'
APP_ROOT/foi-for-councils-2018-10-25T05-16-26/app/services/generate_foi_suggestion.rb:8:in `from_request'
APP_ROOT/foi-for-councils-2018-10-25T05-16-26/app/models/foi_suggestion.rb:13:in `from_request'
APP_ROOT/foi-for-councils-2018-10-25T05-16-26/app/controllers/foi/suggestions_controller.rb:14:in `index'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:194:in `process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:132:in `run_callbacks'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.0/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:134:in `process'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.0/lib/action_view/rendering.rb:32:in `process'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal.rb:191:in `dispatch'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_controller/metal.rb:252:in `dispatch'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:34:in `serve'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:52:in `block in serve'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `each'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `serve'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:840:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:190:in `call!'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/omniauth-1.8.1/lib/omniauth/builder.rb:63:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/exception_notification-4.2.2/lib/exception_notification/rack.rb:41:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/conditional_get.rb:25:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/cookies.rb:670:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:98:in `run_callbacks'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:38:in `call_app'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `block in call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
APP_ROOT/shared/vendor/bundle/ruby/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

-------------------------------
Data:
-------------------------------

* data: {}
```

### PR DESCRIPTION
**Pull request by gbp**
Fixes #200 

If keywords contain boolean operators characters then it could result in invalid tsquery. 

Given the keywords:
`a's & bs'`, `aye | hello`, `yes & ! no`, `foo&bar baz`, `two words`, `this & that thing`, `! nah1`, `!nah2`

These changes will turn the tsquery from:
`(a's & & & bs') | (aye & | & hello) |  (yes & & & ! & no) | (foo&bar & baz) | (two & words) | (this & & & that & thing) | (! & nah1) | (!nah2)`
which is invalid

To:
`('a''s'  &  'bs''') | ('aye'  |  'hello') | ('yes'  &  !  'no') | ('foo&bar baz') | ('two' & 'words') | ('this'  &  'that thing') | (!  'nah1') | ('!nah2')`
which is valid

### CODE REVIEW

File: spec/services/generate_foi_suggestion_spec.rb [hunk 1]
```diff
@@ -118,6 +118,46 @@ def suggest(*args)
...
+
+    context 'resource with NOT boolean operator in keyword' do
+      let!(:link) { create(:curated_link, keywords: '! baz') }
+
+      it 'returns matches to keywords' do
+        # This spec is here to check the query isn't broken.
+        # We're expecting the resource to match the link due to how ts_highlight
+        # works. It will highlights any matching part of the input string,
+        # including those for NOT operations. This means we can't support the
+        # NOT operation with out currently implementation.
```
Comment (garethrees) [inline spec/services/generate_foi_suggestion_spec.rb]: minor typos:

```diff
- NOT operation with out currently implementation
+ NOT operation with our current implementation
```

Comment (gbp) [reply spec/services/generate_foi_suggestion_spec.rb]: Fixes in b6a3359
