### PR TITLE
Prevent PG errors when generating suggestions

### LINKED ISSUE #132: ActiveRecord::StatementInvalid occurred in suggestions#index
PG error caused by keywords being NULL or blank.

```
An ActiveRecord::StatementInvalid occurred in suggestions#index:

  PG::SyntaxError: ERROR:  syntax error in tsquery: "()"
: SELECT request_matches, relevance, curated_links.*
FROM curated_links,
LATERAL (SELECT ARRAY_AGG(DISTINCT rm[1])
FROM (SELECT ts_headline(LOWER(body), to_tsquery((SELECT array_to_string(ARRAY_AGG(
  '(' || regexp_replace(keyword, ' +', ' & ', 'g') || ')'
), ' | ')
FROM (SELECT DISTINCT UNNEST(regexp_split_to_array(keywords, ', *'))
FROM curated_links _cl
WHERE _cl.id = curated_links.id
) AS T(keyword)
)))
FROM foi_requests
WHERE foi_requests.id = 73
LIMIT 1
) AS T(headline)
CROSS JOIN LATERAL regexp_matches(headline, '<b>(.*?)</b>', 'g') AS rm(matches)
) AS T1(request_matches),
LATERAL (SELECT ts_rank(
  setweight(to_tsvector(title), 'B') ||
  setweight(to_tsvector(COALESCE(summary, '')), 'C') ||
  setweight(to_tsvector(keywords), 'A'),
  to_tsquery(array_to_string(request_matches, ' & '))
)
) AS T2(relevance)
WHERE relevance > 0.5
ORDER BY relevance DESC
LIMIT 3

  app/services/foi_suggestion.rb:18:in `from_request'


-------------------------------
Request:
-------------------------------

  * URL        : https://hackney-foi.staging.mysociety.org/foi/request/suggestions
  * HTTP Method: GET
  * IP address : 2a02:c7d:253:af00:ad26:9def:46b8:6554
  * Parameters : {"controller"=>"foi/suggestions", "action"=>"index"}
  * Timestamp  : 2018-06-12 16:09:02 UTC
  * Server : owl
  * Rails root : /data/vhost/hackney-foi.staging.mysociety.org/foi-for-councils-2018-06-12T14-46-17
  * Process: 24366

-------------------------------
Backtrace:
-------------------------------

  app/services/foi_suggestion.rb:18:in `from_request'
  app/controllers/foi/suggestions_controller.rb:14:in `index'


```

### PR DESCRIPTION
**Pull request by gbp**
Fixes #132

Error was caused by curated links without keywords

### CODE REVIEW

File: spec/services/foi_suggestion_spec.rb [hunk 1]
```diff
@@ -92,5 +92,12 @@ def suggest(body)
       expect(s2).to match [l1, l2]
       expect(s3).to match [l2, l1]
     end
+
+    context 'curated link without keyword' do
+      it 'does not raise error' do
```
Comment (crowbot) [inline spec/services/foi_suggestion_spec.rb]: We should probably test for the behaviour we actually want here, rather than not raising an error. So, in this case, empty suggestions?

Comment (gbp) [reply spec/services/foi_suggestion_spec.rb]: Agreed. Changed in e7333c7c728159ebf489af0ee0604456c7dff4fc

**Comment by gbp** [comment]
@crowbot good idea not to prevent submission if we have problems with the full text searching. e9addf2f9c7f7af23db62aca2bfa18786d151a75 is now rescuing `ActiveRecord::StatementInvalid` errors.
