### PR TITLE
[#89] Swtich to DB locking

### LINKED ISSUE #83: Slow processing of Sidekiq jobs
## Option 1: Remove Locking

Commenting out the locking code makes the job complete pretty much instantly.

Locking was introduced in https://github.com/mysociety/foi-for-councils/commit/fa33f14fd78d73c1bbb1b58cc22fd30a5dbca064 as part of https://github.com/mysociety/foi-for-councils/pull/66.

The original implementation of https://github.com/mysociety/foi-for-councils/pull/66 included a worker (`QueueSubmissionsWorker`) to queue any `unqueued` and `queued` `Submission` records, so that all failure cases are handled.

I _think_ the locking was guarding against the case where we re-queue a `queued` `Submission`. The failure case here was losing Redis. In that case, we'd need to requeue `queued` because that `Submission` would have been on the Redis queue, but not yet processed. In normal operation we'd end up duplicating items, hence the need for locking.

During review, we [decided](https://github.com/mysociety/foi-for-councils/pull/66#pullrequestreview-117568572) to reduce the scope of `QueueSubmissionsWorker` to queue only `unqueued` `Submission` records to simplify the code and specs. We couldn't find a reliable way to figure out if a job was already queued (until it was being processed and therefore locked).

So, given we'd handle a Redis outage by manually requeuing any `queued` `Submission` records, I don't think we need to worry about any duplicate jobs existing.

SUBMIT FORM
 * set submission to queued
 * try to put job on redis queue
 * SUCCESS
   * Job gets put on queue
   * Process job
   * Set submission to delivered
 * FAILURE: API DOWN
   * Job gets put on queue
   * Process job
   * Raise exception
   * Sidekiq retry 25 times
   * Move to Dead Jobs if still failing
   * RECOVER BY: Investigate; Fix problem / wait; Manually resend Dead Jobs.
 * FAILURE: REDIS CONNECTION ISSUE
   * No job on queue
   * Rollback submission to unqueued
   * RECOVER BY: `QueueSubmissionsWorker` will re-queue this automatically
   * No locking conflict as this job never made it to the queue
 * FAILURE: REDIS GONE
   * Job gets put on queue
   * Redis disappears & loses all state
   * Submission is stil "queued" in the DB
   * RECOVER BY: Manually re-queue all queued jobs
   * No locking conflict because there won't be any existing jobs on the queue

Instead of locking, I think we could do a [final check](https://github.com/mperham/sidekiq/wiki/Best-Practices#2-make-your-job-idempotent-and-transactional) before delivering:

```ruby
  def deliver
    DeliverSubmission.new(self).call if deliverable?
  end
```

### LINKED ISSUE #89: Indefinitely queued submission
```sql
hackney-foi=> select * from submissions;
 id |   state   |         created_at         |         updated_at         | reference
----+-----------+----------------------------+----------------------------+-----------
  3 | delivered | 2018-05-10 08:59:58.026492 | 2018-05-10 09:02:22.083645 | FOI-28
  2 | delivered | 2018-05-09 16:02:05.037266 | 2018-05-10 11:24:15.895327 | FOI-29
  4 | delivered | 2018-05-10 11:37:03.463626 | 2018-05-10 11:37:56.272903 | FOI-30
  5 | delivered | 2018-05-11 15:06:55.203368 | 2018-05-11 15:06:55.850045 | FOI-1
  6 | delivered | 2018-05-14 08:41:44.745176 | 2018-05-14 08:41:46.92056  | FOI-1
  7 | delivered | 2018-05-14 08:46:56.996831 | 2018-05-14 08:46:57.750331 | FOI-2
  8 | delivered | 2018-05-14 08:50:31.650554 | 2018-05-14 08:50:34.63826  | FOI-3
  9 | delivered | 2018-05-14 08:55:45.183749 | 2018-05-14 08:55:47.073799 | FOI-4
 10 | delivered | 2018-05-14 08:57:24.258581 | 2018-05-14 08:57:26.120415 | FOI-5
 11 | delivered | 2018-05-14 08:59:44.409577 | 2018-05-14 08:59:46.17798  | FOI-6
 12 | delivered | 2018-05-14 09:02:29.607893 | 2018-05-14 09:02:31.288233 | FOI-7
 13 | queued    | 2018-05-14 09:10:17.746326 | 2018-05-14 09:10:17.746326 |
 14 | delivered | 2018-05-14 09:57:57.647272 | 2018-05-14 09:57:59.643056 | FOI-8
```

Submission 13 got created at `09:10:17` – an hour has passed and it still shows as queued, with no `reference`.

No jobs are scheduled for retry:

```ruby
Sidekiq::Stats.new.retry_size
# => 0
```

### PR DESCRIPTION
**Pull request by gbp**
Fixes #89 
Fixes #83 
Closes #98 

Work taken from PR #98 and comments in #89, merged the implementations and added specs.

One of the main specs from #98 wasn't doing [anything](https://github.com/mysociety/foi-for-councils/pull/98/files#r188967109) so this has been expanded and improved.

### CODE REVIEW

**Comment by gbp** [comment]
CI failing due to #102 not being merged yet.

**Comment by gbp** [comment]
I've merged master (which has Travis CI setup) into this branch to get CI check running and hopefully passing. When merging ad43815 will be rebased out.

File: spec/workers/deliver_submission_worker_spec.rb [hunk 1]
```diff
@@ -40,29 +40,30 @@
...
-      # Prove submission object still has the old state:
+
+      # Prove this in memory submission instance still has the old state:
       expect(submission.state).to eq Submission::QUEUED
-      # Run `perform`, this causes a SQL update to set the reference - see the
-      # before block above
+
+      # Stub `Submission#deliver`as calling the original implementation isn't
+      # any good as it would try create a remote request which is obviously
+      # outside the concern for this test. The stubbed implementation ...
```
Comment (garethrees) [inline spec/workers/deliver_submission_worker_spec.rb]: Was this meant to be continued?

File: spec/workers/deliver_submission_worker_spec.rb [hunk 2]
```diff
@@ -40,29 +40,30 @@
...
+
+      # Run the worker job.
       perform
-      # Because we wrap the method call with `with_lock` the object is reloaded,
-      # without this the state would have remain as QUEUED. Prove submission is
-      # in the new state AND has the reference:
+
+      # Because of the `with_lock` block the submission instance gets reloaded.
+      # Without this the state would have remained as QUEUED and saved into the
+      # database. Prove submission is in the state from 1:
```
Comment (garethrees) [inline spec/workers/deliver_submission_worker_spec.rb]: > Prove submission is in the state _from 1_:

Don't quite understand this – I think you mean "Prove submission is in the state set by `Submission.update(state: Submission::DELIVERED)`", and that it can't have been updated by `perform` because we've stubbed the implementation.

Comment (gbp) [reply spec/workers/deliver_submission_worker_spec.rb]: Ooops I had the comment blocks numbered, then I took out for some reason
